import * as React from 'react'

const SearchResultsPage = () => (
  <div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>

  </div>
)

export { SearchResultsPage }